// tslint:disable-next-line:no-unused-expression
export let text;
text = [{
  weekTime: 1,
  dayTime: 1,
  subject: '1',
  courseName: 'INFO6150',
  courseNumber: '6150',
  courseDetail: 'Web Design',
}, {
  weekTime: 2,
  dayTime: 2,
  subject: '1',
  courseName: 'INFO5100',
  courseNumber: '5100',
  courseDetail: 'Java',
}, {
  weekTime: 3,
  dayTime: 3,
  subject: '1',
  courseName: 'INFO6105',
  courseNumber: '6105',
  courseDetail: 'Data Science',
}, {
  weekTime: 4,
  dayTime: 4,
  subject: '1',
  courseName: 'INFO6210',
  courseNumber: '6210',
  courseDetail: 'Database',
}, {
  weekTime: 5,
  dayTime: 5,
  subject: '1',
  courseName: 'INFO5101',
  courseNumber: '5101',
  courseDetail: 'Java Lab',
}, {
  weekTime: 5,
  dayTime: 6,
  subject: '1',
  courseName: 'INFO6250',
  courseNumber: '6250',
  courseDetail: 'Software Quality Control',
}, {
  weekTime: 2,
  dayTime: 1,
  subject: '2',
  courseName: 'INFO6111',
  courseNumber: '6111',
  courseDetail: 'Web',
}, {
  weekTime: 3,
  dayTime: 1,
  subject: '1',
  courseName: 'INFO7010',
  courseNumber: '7010',
  courseDetail: 'Design',
}, {
  weekTime: 4,
  dayTime: 1,
  subject: '1',
  courseName: 'INFO6150',
  courseNumber: '6100',
  courseDetail: 'DB',
}, {
  weekTime: 5,
  dayTime: 3,
  subject: '1',
  courseName: 'INFO6150',
  courseNumber: '6000',
  courseDetail: 'DS',
}];
